name: Pdf export
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: 27.1

      - uses: actions/checkout@v2

      - name: Export to LaTeX
        run: |
          emacs --batch --eval=" \
          (progn \
            (require 'org) \
            (with-current-buffer \
              (find-file \"ComputationalTrinitarianism.org\") \
              (org-latex-export-to-latex)))"
      - name: Compile to PDF
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ComputationalTrinitarianism.tex
      - name: Store pdf
        uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: ComputationalTrinitarianism.pdf
