name: Pdf export
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: 27.1

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Export to LaTeX
        run: |
          emacs --batch --eval=" \
          (progn \
            (require 'org) \
            (with-current-buffer \
              (find-file \"Thesis.org\") \
              (org-latex-export-to-latex)))"

      - uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile to PDF
        run: tectonic Thesis.tex

      - name: Create Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: v${{ github.run_number }}
          draft: false
          prerelease: true

      - name: Populate Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./Thesis.pdf
          asset_name: Thesis.pdf
          asset_content_type: application/pdf
